version: "3.1"
services:
  web: 
    build: .
    ports:
      - "40:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - net-clinica-sso
networks:
  net-clinica-sso:
    driver: bridge
  db-mysql:
    driver: bridge
volumes:
  persistent:



        
